image: gcc
variables:
  MEM_BW: 5
  PEAK_SCALAR: 5
  SIMD_LEN_BITS: 256
  
stages:
  - tests
  - benchmark
  - profile



compare:
  stage: tests
  script:
    - cd 2D
    - sudo apt update && sudo apt install -y python3 python3-pip python3.10-venv 
    - python3 -m venv venv && source venv/bin/activate
    - pip install -r requirements.txt
    - make test
  only:
    - merge_requests
    - main
    - branches

leaks:
  stage: tests
  script:
    - cd 2D && sudo apt update && sudo apt install -y valgrind
    - make leaks
  only:
    - merge_requests
    - main
    - branches

benchmark:
  stage: benchmark
  artifacts:
    paths:
      - 2D/artifacts/*
  script:
    - cd 2D
    - sudo apt update && sudo apt install -y python3 python3-pip python3.10-venv 
    - python3 -m venv venv && source venv/bin/activate
    - pip install -r requirements.txt
    - make benchmark
  only:
    - merge_requests
    - main

profile:
  stage: profile
  script:
    - cd 2D && make profile
  only:
    - merge_requests
    - main